import AsyncStorage from '@react-native-async-storage/async-storage';
import React, {createContext, ReactNode, useContext, useEffect, useMemo, useState} from 'react';

export type LanguageCode = 'en' | 'hi';

const LANGUAGE_STORAGE_KEY = '@app_language';

const translations = {
  en: {
    home: 'Home',
    tasks: 'Tasks',
    lands: 'Lands',
    team: 'Team',
    profile: 'Profile',
    profileSubtitle: 'View and manage your profile information',
    fieldExecutive: 'Field Executive',
    account: 'Account',
    personalInformation: 'Personal Information',
    personalInformationSub: 'View and update your personal details',
    changePassword: 'Change Password',
    changePasswordSub: 'Update your account password',
    contactInformation: 'Contact Information',
    contactInformationSub: 'Manage your phone and email',
    notificationSettings: 'Notification Settings',
    notificationSettingsSub: 'Manage your notification preferences',
    language: 'Language',
    languageSub: 'Change app language',
    english: 'English',
    hindi: 'Hindi',
    support: 'Support',
    helpSupport: 'Help & Support',
    helpSupportSub: 'Get help and find answers',
    termsConditions: 'Terms & Conditions',
    termsConditionsSub: 'View terms and conditions',
    privacyPolicy: 'Privacy Policy',
    privacyPolicySub: 'View privacy policy',
    aboutApp: 'About App',
    version: 'Version 1.0.0',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    notifications: 'Notifications',
    notificationMessage: 'You have 3 new notifications.',
    chooseLanguage: 'Choose Language',
    languageChanged: 'Language changed successfully.',
    landsSubtitle: 'View and manage assigned lands',
    assignedLands: 'My Assigned Lands (6)',
    location: 'Location',
    farmerName: 'Farmer Name',
    crop: 'Crop',
    area: 'Area',
    acres: 'Acres',
    ownerDetails: 'Owner Details',
    ownerName: 'Owner Name',
    phone: 'Phone',
    staffAssigned: 'Staff Assigned',
    labourAssigned: 'Labour Assigned',
    labourers: 'Labourers',
    supervisor: 'Supervisor',
    landDetails: 'Land Details',
    soilType: 'Soil Type',
    photographs: 'Photographs',
    irrigation: 'Irrigation',
    goodMorning: 'Good Morning,',
    fieldManager: 'Field Manager',
    attendance: 'Attendance',
    checkedOutSuccess: 'You have checked out successfully.',
    checkedInSuccess: 'You have checked in successfully.',
    selfAttendance: 'SELF ATTENDANCE',
    checkedIn: 'Checked In',
    checkedOut: 'Checked Out',
    todayDate: 'Today, 21 May 2025',
    checkInTime: 'Check-in Time',
    checkOutTime: 'Check-out Time',
    workingDuration: 'Working Duration',
    totalDuration: 'Total Duration',
    checkOut: 'CHECK OUT',
    checkIn: 'CHECK IN',
    todaysSummary: "TODAY'S SUMMARY",
    viewAll: 'View All',
    pendingTasks: 'Pending Tasks',
    pendingFieldVisits: 'Pending Field Visits',
    attendanceApprovals: 'Attendance Approvals',
    billsPending: 'Bills Pending',
    quickActions: 'QUICK ACTIONS',
    approveAttendance: 'Approve Attendance',
    approvalsPending: '5 approvals pending',
    vehicleLogBook: 'Vehicle Log Book',
    vehicleLogBookSub: 'Add trip and fuel details',
    addEntry: 'Add Entry',
    fuelEntry: 'Fuel Entry',
    uploadBillLabel: 'Upload Bill',
    odometerImage: 'Odometer Image',
    tapToUpload: 'Tap to upload',
    saveEntry: 'Save Entry',
    saveFuelEntry: 'Save Fuel Entry',
    entrySaved: 'Entry saved successfully.',
    fuelEntrySaved: 'Fuel entry saved successfully.',
    fuelQuantity: 'Fuel Quantity',
    billAmount: 'Bill Amount',
    fuelStation: 'Fuel Station',
    active: 'Active',
    totalKm: 'Total KM',
    thisMonth: 'This Month',
    fuelThisMonth: 'Fuel This Month',
    fuelCost: 'Fuel Cost',
    mileage: 'Mileage',
    logEntries: 'Log Entries',
    filter: 'Filter',
    fieldVisit: 'Field Visit',
    monthlySummary: 'May 2025 Summary',
    vehicleSummary: 'Vehicle Summary',
    previousMonthData: 'Previous month: 568 km  •  56.0 L  •  10.1 km/L',
    uploadBill: 'Reimbursement',
    raiseTicket: 'Raise a Ticket',
    raiseRequest: 'Raise a Request',
    myRequests: 'My Requests',
    requestType: 'Request Type',
    repair: 'Repair',
    mishappening: 'Mishappening',
    insectAttack: 'Insect Attack',
    fungusBacteriaInfection: 'Fungus/Bacteria Infection',
    landDispute: 'Land Dispute',
    transportVehicle: 'Transport / Vehicle',
    transportVehicleSub: 'Request for vehicle, fuel, or transport related support',
    reimbursementRequestSub: 'Request for expense reimbursement',
    equipmentMaterial: 'Equipment / Material',
    equipmentMaterialSub: 'Request for tools, equipment or field materials',
    hrAdmin: 'HR / Admin',
    hrAdminSub: 'General HR or administrative related requests',
    requestDetails: 'Request Details',
    subject: 'Subject',
    description: 'Description',
    selectLand: 'Select Land',
    priority: 'Priority',
    normal: 'Normal',
    low: 'Low',
    high: 'High',
    urgent: 'Urgent',
    attachmentOptional: 'Attachment (Optional)',
    uploadFile: 'Upload File',
    uploadImageOne: 'Upload Image 1',
    uploadImageTwo: 'Upload Image 2',
    uploadVideo: 'Upload Video',
    fileHint: 'JPG, PNG, PDF up to 5MB',
    submitRequest: 'Submit Request',
    requestSubmitted: 'Request submitted successfully.',
    newRequest: 'New Request',
    inProgress: 'In Progress',
    applyLeave: 'Apply for Leave',
    myLeaves: 'My Leaves',
    leaveBalance: 'Leave Balance',
    casualLeave: 'Casual Leave',
    sickLeave: 'Sick Leave',
    earnedLeave: 'Earned Leave',
    daysAvailable: 'Days Available',
    leaveDetails: 'Leave Details',
    leaveType: 'Leave Type',
    selectLeaveType: 'Select Leave Type',
    fromDate: 'From Date',
    selectFromDate: 'Select From Date',
    toDate: 'To Date',
    selectToDate: 'Select To Date',
    halfDay: 'Half Day',
    reason: 'Reason',
    leaveReasonPlaceholder: 'Enter reason for leave',
    note: 'Note',
    leaveNote: 'Make sure to apply leave in advance for smoother approval.',
    submitLeaveRequest: 'Submit Leave Request',
    leaveSubmitted: 'Leave request submitted successfully.',
    newClaim: 'New Claim',
    totalClaims: 'Total Claims',
    approvedClaims: 'Approved',
    pendingClaims: 'Pending',
    all: 'All',
    rejected: 'Rejected',
    claimId: 'Claim ID',
    purpose: 'Purpose',
    submittedOn: 'Submitted on',
    documents: 'Documents',
    viewDetails: 'View Details',
    fuelReimbursement: 'Fuel Reimbursement',
    travelAllowance: 'Travel Allowance',
    otherExpenses: 'Other Expenses',
    claimType: 'Claim Type',
    food: 'Food',
    fuel: 'Fuel',
    travel: 'Travel',
    other: 'Other',
    amount: 'Amount',
    claimSaved: 'Claim saved successfully.',
    billsPendingShort: '2 bills pending',
    nextTask: 'NEXT TASK',
    landSurvey: 'Land Survey',
    villageBori: 'Village: Bori',
    dueToday: 'Due Today',
    overdue: 'Overdue',
    upcoming: 'Upcoming',
    openTask: 'Open Task',
    monthlyAttendance: 'Monthly Attendance',
    may2025: 'May 2025',
    present: 'Present',
    absent: 'Absent',
    off: 'Off',
    tasksSubtitle: 'View and manage your assigned tasks',
    taskNotifications: 'You have 3 task notifications.',
    assigned: 'Assigned',
    pending: 'Pending',
    completed: 'Completed',
    farmId: 'Farm ID',
    dueTime: 'Due Time',
    taskDetails: 'Task Details',
    farmer: 'Farmer',
    assignedTo: 'Assigned To',
    assignStaff: 'Assign Staff',
    workInstructions: 'Work Instructions',
    startTask: 'Start Task',
    workPending: 'Work Pending',
    taskStarted: 'Task Started',
    taskAllocation: 'Task Allocation',
    farmLocation: 'Farm Location',
    teamSubtitle: 'View your team members',
    teamNotifications: 'You have 3 team notifications.',
    teamMembers: 'team members',
    supervisorRole: 'Supervisor',
    driver: 'Driver',
    labour: 'Labour',
    approved: 'Approved',
    approve: 'Approve',
    attendanceApproved: 'Attendance Approved',
    loginScreen: 'Login Screen',
    login: 'Login',
    loadingDashboard: 'Loading your dashboard',
  },
  hi: {
    home: 'होम',
    tasks: 'कार्य',
    lands: 'भूमि',
    team: 'टीम',
    profile: 'प्रोफाइल',
    profileSubtitle: 'अपनी प्रोफाइल जानकारी देखें और प्रबंधित करें',
    fieldExecutive: 'फील्ड एग्जीक्यूटिव',
    account: 'खाता',
    personalInformation: 'व्यक्तिगत जानकारी',
    personalInformationSub: 'अपनी व्यक्तिगत जानकारी देखें और अपडेट करें',
    changePassword: 'पासवर्ड बदलें',
    changePasswordSub: 'अपने खाते का पासवर्ड अपडेट करें',
    contactInformation: 'संपर्क जानकारी',
    contactInformationSub: 'फोन और ईमेल प्रबंधित करें',
    notificationSettings: 'सूचना सेटिंग्स',
    notificationSettingsSub: 'सूचना पसंद प्रबंधित करें',
    language: 'भाषा',
    languageSub: 'ऐप की भाषा बदलें',
    english: 'अंग्रेजी',
    hindi: 'हिंदी',
    support: 'सहायता',
    helpSupport: 'मदद और सहायता',
    helpSupportSub: 'मदद और जवाब प्राप्त करें',
    termsConditions: 'नियम और शर्तें',
    termsConditionsSub: 'नियम और शर्तें देखें',
    privacyPolicy: 'गोपनीयता नीति',
    privacyPolicySub: 'गोपनीयता नीति देखें',
    aboutApp: 'ऐप के बारे में',
    version: 'संस्करण 1.0.0',
    logout: 'लॉगआउट',
    logoutConfirm: 'क्या आप लॉगआउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    notifications: 'सूचनाएं',
    notificationMessage: 'आपके पास 3 नई सूचनाएं हैं।',
    chooseLanguage: 'भाषा चुनें',
    languageChanged: 'भाषा सफलतापूर्वक बदल गई।',
    landsSubtitle: 'सौंपी गई भूमि देखें और प्रबंधित करें',
    assignedLands: 'मेरी सौंपी गई भूमि (6)',
    location: 'स्थान',
    farmerName: 'किसान का नाम',
    crop: 'फसल',
    area: 'क्षेत्रफल',
    acres: 'एकड़',
    ownerDetails: 'मालिक विवरण',
    ownerName: 'मालिक का नाम',
    phone: 'फोन',
    staffAssigned: 'नियुक्त स्टाफ',
    labourAssigned: 'नियुक्त मजदूर',
    labourers: 'मजदूर',
    supervisor: 'सुपरवाइजर',
    landDetails: 'भूमि विवरण',
    soilType: 'मिट्टी का प्रकार',
    photographs: 'फोटो',
    irrigation: 'सिंचाई',
    goodMorning: 'सुप्रभात,',
    fieldManager: 'फील्ड मैनेजर',
    attendance: 'उपस्थिति',
    checkedOutSuccess: 'आपने सफलतापूर्वक चेक आउट किया।',
    checkedInSuccess: 'आपने सफलतापूर्वक चेक इन किया।',
    selfAttendance: 'स्वयं उपस्थिति',
    checkedIn: 'चेक इन',
    checkedOut: 'चेक आउट',
    todayDate: 'आज, 21 मई 2025',
    checkInTime: 'चेक-इन समय',
    checkOutTime: 'चेक-आउट समय',
    workingDuration: 'कार्य अवधि',
    totalDuration: 'कुल अवधि',
    checkOut: 'चेक आउट',
    checkIn: 'चेक इन',
    todaysSummary: 'आज का सारांश',
    viewAll: 'सभी देखें',
    pendingTasks: 'लंबित कार्य',
    pendingFieldVisits: 'लंबित फील्ड विजिट',
    attendanceApprovals: 'उपस्थिति अनुमोदन',
    billsPending: 'लंबित बिल',
    quickActions: 'त्वरित कार्य',
    approveAttendance: 'उपस्थिति मंजूर करें',
    approvalsPending: '5 अनुमोदन लंबित',
    vehicleLogBook: 'वाहन लॉग बुक',
    vehicleLogBookSub: 'यात्रा और ईंधन विवरण जोड़ें',
    addEntry: 'नई एंट्री',
    fuelEntry: 'ईंधन एंट्री',
    uploadBillLabel: 'बिल अपलोड करें',
    odometerImage: 'ओडोमीटर फोटो',
    tapToUpload: 'अपलोड करने के लिए टैप करें',
    saveEntry: 'एंट्री सेव करें',
    saveFuelEntry: 'ईंधन एंट्री सेव करें',
    entrySaved: 'एंट्री सफलतापूर्वक सेव हुई।',
    fuelEntrySaved: 'ईंधन एंट्री सफलतापूर्वक सेव हुई।',
    fuelQuantity: 'ईंधन मात्रा',
    billAmount: 'बिल राशि',
    fuelStation: 'ईंधन स्टेशन',
    active: 'सक्रिय',
    totalKm: 'कुल किमी',
    thisMonth: 'इस महीने',
    fuelThisMonth: 'इस महीने ईंधन',
    fuelCost: 'ईंधन खर्च',
    mileage: 'माइलेज',
    logEntries: 'लॉग एंट्री',
    filter: 'फिल्टर',
    fieldVisit: 'फील्ड विजिट',
    monthlySummary: 'मई 2025 सारांश',
    vehicleSummary: 'वाहन सारांश',
    previousMonthData: 'पिछला महीना: 568 किमी  •  56.0 L  •  10.1 किमी/L',
    uploadBill: 'प्रतिपूर्ति',
    raiseTicket: 'टिकट उठाएं',
    raiseRequest: 'अनुरोध उठाएं',
    myRequests: 'मेरे अनुरोध',
    requestType: 'अनुरोध प्रकार',
    repair: 'मरम्मत',
    mishappening: 'दुर्घटना',
    insectAttack: 'कीट हमला',
    fungusBacteriaInfection: 'फंगस/बैक्टीरिया संक्रमण',
    landDispute: 'भूमि विवाद',
    transportVehicle: 'परिवहन / वाहन',
    transportVehicleSub: 'वाहन, ईंधन या परिवहन सहायता के लिए अनुरोध',
    reimbursementRequestSub: 'खर्च प्रतिपूर्ति के लिए अनुरोध',
    equipmentMaterial: 'उपकरण / सामग्री',
    equipmentMaterialSub: 'टूल्स, उपकरण या फील्ड सामग्री के लिए अनुरोध',
    hrAdmin: 'एचआर / एडमिन',
    hrAdminSub: 'सामान्य एचआर या प्रशासनिक अनुरोध',
    requestDetails: 'अनुरोध विवरण',
    subject: 'विषय',
    description: 'विवरण',
    selectLand: 'भूमि चुनें',
    priority: 'प्राथमिकता',
    normal: 'सामान्य',
    low: 'कम',
    high: 'उच्च',
    urgent: 'तत्काल',
    attachmentOptional: 'अटैचमेंट (वैकल्पिक)',
    uploadFile: 'फाइल अपलोड करें',
    uploadImageOne: 'इमेज 1 अपलोड करें',
    uploadImageTwo: 'इमेज 2 अपलोड करें',
    uploadVideo: 'वीडियो अपलोड करें',
    fileHint: 'JPG, PNG, PDF 5MB तक',
    submitRequest: 'अनुरोध जमा करें',
    requestSubmitted: 'अनुरोध सफलतापूर्वक जमा हुआ।',
    newRequest: 'नया अनुरोध',
    inProgress: 'प्रगति में',
    applyLeave: 'छुट्टी आवेदन',
    myLeaves: 'मेरी छुट्टियां',
    leaveBalance: 'छुट्टी बैलेंस',
    casualLeave: 'आकस्मिक छुट्टी',
    sickLeave: 'बीमारी छुट्टी',
    earnedLeave: 'अर्जित छुट्टी',
    daysAvailable: 'दिन उपलब्ध',
    leaveDetails: 'छुट्टी विवरण',
    leaveType: 'छुट्टी प्रकार',
    selectLeaveType: 'छुट्टी प्रकार चुनें',
    fromDate: 'तारीख से',
    selectFromDate: 'आरंभ तारीख चुनें',
    toDate: 'तारीख तक',
    selectToDate: 'अंतिम तारीख चुनें',
    halfDay: 'आधा दिन',
    reason: 'कारण',
    leaveReasonPlaceholder: 'छुट्टी का कारण दर्ज करें',
    note: 'नोट',
    leaveNote: 'बेहतर स्वीकृति के लिए छुट्टी पहले से आवेदन करें।',
    submitLeaveRequest: 'छुट्टी अनुरोध जमा करें',
    leaveSubmitted: 'छुट्टी अनुरोध सफलतापूर्वक जमा हुआ।',
    newClaim: 'नया दावा',
    totalClaims: 'कुल दावे',
    approvedClaims: 'स्वीकृत',
    pendingClaims: 'लंबित',
    all: 'सभी',
    rejected: 'अस्वीकृत',
    claimId: 'दावा आईडी',
    purpose: 'उद्देश्य',
    submittedOn: 'जमा किया गया',
    documents: 'दस्तावेज',
    viewDetails: 'विवरण देखें',
    fuelReimbursement: 'ईंधन प्रतिपूर्ति',
    travelAllowance: 'यात्रा भत्ता',
    otherExpenses: 'अन्य खर्च',
    claimType: 'दावा प्रकार',
    food: 'भोजन',
    fuel: 'ईंधन',
    travel: 'यात्रा',
    other: 'अन्य',
    amount: 'राशि',
    claimSaved: 'दावा सफलतापूर्वक सेव हुआ।',
    billsPendingShort: '2 बिल लंबित',
    nextTask: 'अगला कार्य',
    landSurvey: 'भूमि सर्वेक्षण',
    villageBori: 'गांव: बोरी',
    dueToday: 'आज देय',
    overdue: 'देरी से',
    upcoming: 'आगामी',
    openTask: 'कार्य खोलें',
    monthlyAttendance: 'मासिक उपस्थिति',
    may2025: 'मई 2025',
    present: 'उपस्थित',
    absent: 'अनुपस्थित',
    off: 'अवकाश',
    tasksSubtitle: 'अपने सौंपे गए कार्य देखें और प्रबंधित करें',
    taskNotifications: 'आपके पास 3 कार्य सूचनाएं हैं।',
    assigned: 'सौंपे गए',
    pending: 'लंबित',
    completed: 'पूर्ण',
    farmId: 'फार्म आईडी',
    dueTime: 'देय समय',
    taskDetails: 'कार्य विवरण',
    farmer: 'किसान',
    assignedTo: 'सौंपा गया',
    assignStaff: 'स्टाफ सौंपें',
    workInstructions: 'कार्य निर्देश',
    startTask: 'कार्य शुरू करें',
    workPending: 'कार्य लंबित',
    taskStarted: 'कार्य शुरू',
    taskAllocation: 'कार्य आवंटन',
    farmLocation: 'फार्म स्थान',
    teamSubtitle: 'अपनी टीम के सदस्यों को देखें',
    teamNotifications: 'आपके पास 3 टीम सूचनाएं हैं।',
    teamMembers: 'टीम सदस्य',
    supervisorRole: 'सुपरवाइजर',
    driver: 'ड्राइवर',
    labour: 'मजदूर',
    approved: 'मंजूर',
    approve: 'मंजूर करें',
    attendanceApproved: 'उपस्थिति मंजूर',
    loginScreen: 'लॉगिन स्क्रीन',
    login: 'लॉगिन',
    loadingDashboard: 'आपका डैशबोर्ड लोड हो रहा है',
  },
};

type TranslationKey = keyof typeof translations.en;

type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => Promise<void>;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({children}: {children: ReactNode}) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_STORAGE_KEY).then(savedLanguage => {
      if (savedLanguage === 'en' || savedLanguage === 'hi') {
        setLanguageState(savedLanguage);
      }
    });
  }, []);

  const setLanguage = async (nextLanguage: LanguageCode) => {
    setLanguageState(nextLanguage);
    await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey) => translations[language][key],
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
